# Generated by Django 5.1.3 on 2024-11-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rating", models.DecimalField(decimal_places=2, max_digits=4)),
                ("stock", models.IntegerField()),
                ("brand", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=100)),
                ("weight", models.FloatField()),
                ("warranty_information", models.TextField()),
                ("shipping_information", models.TextField()),
                ("availability_status", models.CharField(max_length=100)),
                ("return_policy", models.TextField()),
                ("minimum_order_quantity", models.IntegerField()),
                ("thumbnail", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("barcode", models.CharField(max_length=100)),
                ("qrCode", models.CharField(max_length=100)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("url", models.ImageField(upload_to="images/")),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=4)),
                ("comment", models.TextField()),
                ("date", models.DateField()),
                ("reviewer_name", models.CharField(max_length=100)),
                ("reviewer_email", models.EmailField(max_length=254)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.product"
                    ),
                ),
            ],
        ),
    ]
