# Generated by Django 5.1.3 on 2024-11-12 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_category_remove_product_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimension",
            old_name="product_id",
            new_name="productId",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="product_id",
            new_name="productId",
        ),
        migrations.RenameField(
            model_name="meta",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="meta",
            old_name="product_id",
            new_name="productId",
        ),
        migrations.RenameField(
            model_name="meta",
            old_name="updated_at",
            new_name="updatedAt",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="availability_status",
            new_name="availabilityStatus",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category_id",
            new_name="categoryId",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="discount_percentage",
            new_name="discountPercentage",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="minimum_order_quantity",
            new_name="minimumOrderQuantity",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="return_policy",
            new_name="returnPolicy",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="shipping_information",
            new_name="shippingInformation",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="warranty_information",
            new_name="warrantyInformation",
        ),
        migrations.RenameField(
            model_name="producttag",
            old_name="product_id",
            new_name="productId",
        ),
        migrations.RenameField(
            model_name="producttag",
            old_name="tag_id",
            new_name="tagId",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="product_id",
            new_name="productId",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="reviewer_email",
            new_name="reviewerEmail",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="reviewer_name",
            new_name="reviewerName",
        ),
    ]
