# Generated by Django 5.1.3 on 2024-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0004_alter_category_id_alter_dimension_id_alter_image_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimension",
            old_name="productId",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="productId",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="meta",
            old_name="productId",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="categoryId",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="producttag",
            old_name="productId",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="productId",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="meta",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
