# Generated by Django 5.1.3 on 2024-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0005_rename_productid_dimension_product_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_title_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_tag_name"
            ),
        ),
    ]
