# Generated by Django 5.1.3 on 2024-11-12 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0008_rename_dimension_dimensions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimensions",
            old_name="length",
            new_name="depth",
        ),
    ]
