# Generated by Django 5.1.3 on 2024-11-12 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0009_rename_length_dimensions_depth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttag",
            old_name="tagId",
            new_name="tag",
        ),
    ]
