# Generated by Django 5.1.3 on 2024-11-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0010_rename_tagid_producttag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="API.tag"
            ),
        ),
    ]
