# Generated by Django 5.1.3 on 2024-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0012_remove_dimensions_product_remove_meta_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttag",
            name="product",
        ),
        migrations.RemoveField(
            model_name="producttag",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="API.tag"),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dimensions",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="meta",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="AllInOneProduct",
        ),
        migrations.DeleteModel(
            name="productTag",
        ),
    ]
