# Generated by Django 5.1.3 on 2024-11-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0016_alter_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meta",
            name="qrCode",
        ),
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.ImageField(upload_to="qr/")),
                (
                    "meta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="API.meta"
                    ),
                ),
            ],
        ),
    ]
