# Generated by Django 5.1.3 on 2024-11-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_remove_meta_qrcode_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrCode', to='API.meta'),
        ),
    ]
