# Generated by Django 5.1.3 on 2024-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0018_alter_meta_createdat_alter_meta_updatedat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discountPercentage",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(),
        ),
    ]
